### ISSUE TITLE
Stop Streams when not needed

### ISSUE THREAD

**Issue by bjoerns1983** [m1k1o/hls-restream#5]
This is a simple project which does what i want.
But is it somehow possible to stop ffmpeg if no user is connected to the stream anymore?

**Comment by m1k1o** [comment]
This is meant for always on transcoding. There is a different project for that, it does transcoding only when needed: https://github.com/m1k1o/go-transcode

**Comment by bjoerns1983** [comment]
Thanks for the info, i will give it a try.
